require("dotenv").config();
const { MongoClient } = require("mongodb");

const client = new MongoClient(process.env.MONGO_URI);

const songs = {
  name: "Oops I Did It Again",
  artist: "Britney Spears",
  imageurl:
    "https://upload.wikimedia.org/wikipedia/en/2/24/Britney_Spears_-_Oops%21..._I_Did_It_Again.png",
  song: [
    [
      { lyrics: "I", chords: "C#m" },
      { lyrics: "think" },
      { lyrics: "I" },
      { lyrics: "did" },
      { lyrics: "it" },
      { lyrics: "again", chords: "A" },
      { lyrics: "I" },
      { lyrics: "made" },
      { lyrics: "you" },
      { lyrics: "believe", chords: "G#" },
      { lyrics: "were" },
      { lyrics: "more" },
      { lyrics: "than" },
      { lyrics: "just" },
      { lyrics: "friends," },
      { lyrics: "oh" },
      { lyrics: "baby" },
    ],
    [
      { lyrics: "It" },
      { lyrics: "might" },
      { lyrics: "seem" },
      { lyrics: "like" },
      { lyrics: "a" },
      { lyrics: "crush", chords: "C#m" },
      { lyrics: "But" },
      { lyrics: "it" },
      { lyrics: "doesn't" },
      { lyrics: "mean" },
      { lyrics: "that" },
      { lyrics: "I'm" },
      { lyrics: "serious", chords: "A" },
      { lyrics: "", chords: "G#" },
    ],
    // Pre-Chorus
    [
      { lyrics: "Cause", chords: "A" },
      { lyrics: "to" },
      { lyrics: "lose" },
      { lyrics: "all" },
      { lyrics: "my" },
      { lyrics: "senses", chords: "G#" },
      { lyrics: "That" },
      { lyrics: "is" },
      { lyrics: "just" },
      { lyrics: "so" },
      { lyrics: "typically" },
      { lyrics: "me", chords: "B" },
    ],
    [{ lyrics: "Oh", chords: "" }, { lyrics: "baby," }, { lyrics: "baby" }],
    // Chorus
    [
      { lyrics: "Oops!...", chords: "C#m" },
      { lyrics: "I" },
      { lyrics: "did" },
      { lyrics: "it" },
      { lyrics: "again", chords: "G#" },
    ],
    [
      { lyrics: "I" },
      { lyrics: "played" },
      { lyrics: "with" },
      { lyrics: "your" },
      { lyrics: "heart,", chords: "B" },
      { lyrics: "got" },
      { lyrics: "lost" },
      { lyrics: "in" },
      { lyrics: "the" },
      { lyrics: "game", chords: "E" },
    ],
    [{ lyrics: "Oh" }, { lyrics: "baby," }, { lyrics: "baby", chords: "B" }],
    [
      { lyrics: "Oops!...", chords: "E" },
      { lyrics: "you" },
      { lyrics: "think" },
      { lyrics: "I'm" },
      { lyrics: "in" },
      { lyrics: "love", chords: "C#m" },
    ],
    [
      { lyrics: "That" },
      { lyrics: "I'm" },
      { lyrics: "sent" },
      { lyrics: "from" },
      { lyrics: "above", chords: "B" },
    ],
    [
      { lyrics: "I'm" },
      { lyrics: "not" },
      { lyrics: "that" },
      { lyrics: "innocent", chords: "E" },
    ],
    // Verse 2
    [
      { lyrics: "You" },
      { lyrics: "see" },
      { lyrics: "my" },
      { lyrics: "problem" },
      { lyrics: "is" },
      { lyrics: "this", chords: "C#m" },
      { lyrics: "I'm" },
      { lyrics: "dreaming" },
      { lyrics: "away", chords: "A" },
      { lyrics: "Wishing" },
      { lyrics: "that" },
      { lyrics: "heroes," },
      { lyrics: "they" },
      { lyrics: "truly" },
      { lyrics: "exist", chords: "G#" },
    ],
    [
      { lyrics: "I" },
      { lyrics: "cry," },
      { lyrics: "watching" },
      { lyrics: "the" },
      { lyrics: "days", chords: "C#m" },
      { lyrics: "Can't" },
      { lyrics: "you" },
      { lyrics: "see" },
      { lyrics: "I'm" },
      { lyrics: "a" },
      { lyrics: "fool", chords: "A" },
      { lyrics: "in" },
      { lyrics: "so" },
      { lyrics: "many" },
      { lyrics: "ways", chords: "G#" },
    ],
    // Pre-Chorus
    [
      { lyrics: "But", chords: "A" },
      { lyrics: "to" },
      { lyrics: "lose" },
      { lyrics: "all" },
      { lyrics: "my" },
      { lyrics: "senses", chords: "G#" },
      { lyrics: "That" },
      { lyrics: "is" },
      { lyrics: "just" },
      { lyrics: "so" },
      { lyrics: "typically" },
      { lyrics: "me", chords: "B" },
    ],
    [{ lyrics: "Baby," }, { lyrics: "oh" }],
    // Chorus repeated
    [
      { lyrics: "Oops!...", chords: "C#m" },
      { lyrics: "I" },
      { lyrics: "did" },
      { lyrics: "it" },
      { lyrics: "again", chords: "G#" },
    ],
    [
      { lyrics: "I" },
      { lyrics: "played" },
      { lyrics: "with" },
      { lyrics: "your" },
      { lyrics: "heart,", chords: "B" },
      { lyrics: "got" },
      { lyrics: "lost" },
      { lyrics: "in" },
      { lyrics: "the" },
      { lyrics: "game", chords: "E" },
    ],
    [{ lyrics: "Oh" }, { lyrics: "baby," }, { lyrics: "baby", chords: "B" }],
    [
      { lyrics: "Oops!...", chords: "E" },
      { lyrics: "you" },
      { lyrics: "think" },
      { lyrics: "I'm" },
      { lyrics: "in" },
      { lyrics: "love", chords: "C#m" },
    ],
    [
      { lyrics: "That" },
      { lyrics: "I'm" },
      { lyrics: "sent" },
      { lyrics: "from" },
      { lyrics: "above", chords: "B" },
    ],
    [
      { lyrics: "I'm" },
      { lyrics: "not" },
      { lyrics: "that" },
      { lyrics: "innocent", chords: "E" },
    ],
    // Interlude (repeated chords)
    [
      { lyrics: "Yeah", chords: "C#m" },
      { lyrics: "yeah" },
      { lyrics: "yeah" },
      { lyrics: "yeah" },
      { lyrics: "yeah" },
      { lyrics: "yeah", chords: "C#m" },
    ],
    [
      { lyrics: "Yeah", chords: "C#m" },
      { lyrics: "yeah" },
      { lyrics: "yeah" },
      { lyrics: "yeah" },
      { lyrics: "yeah" },
      { lyrics: "yeah", chords: "C#m" },
    ],
    // Spoken section as lyrics only (no chords)
    [{ lyrics: "All aboard!" }],
    [
      { lyrics: "Britney," },
      { lyrics: "before" },
      { lyrics: "you" },
      { lyrics: "go," },
      { lyrics: "there's" },
      { lyrics: "something" },
      { lyrics: "I" },
      { lyrics: "want" },
      { lyrics: "you" },
      { lyrics: "to" },
      { lyrics: "have" },
    ],
    [
      { lyrics: "Oh," },
      { lyrics: "it's" },
      { lyrics: "beautiful," },
      { lyrics: "but" },
      { lyrics: "wait" },
      { lyrics: "a" },
      { lyrics: "minute," },
      { lyrics: "isn't" },
      { lyrics: "this...?" },
    ],
    [
      { lyrics: "Yeah," },
      { lyrics: "yes" },
      { lyrics: "it" },
      { lyrics: "is", chords: "A" },
    ],
    [
      { lyrics: "But" },
      { lyrics: "I" },
      { lyrics: "thought" },
      { lyrics: "the" },
      { lyrics: "old" },
      { lyrics: "lady" },
      { lyrics: "dropped" },
      { lyrics: "it" },
      { lyrics: "into" },
      { lyrics: "the" },
      { lyrics: "ocean" },
      { lyrics: "in" },
      { lyrics: "the" },
      { lyrics: "end", chords: "B" },
    ],
    [
      { lyrics: "Well" },
      { lyrics: "baby," },
      { lyrics: "I" },
      { lyrics: "went" },
      { lyrics: "down" },
      { lyrics: "and" },
      { lyrics: "got" },
      { lyrics: "it" },
      { lyrics: "for" },
      { lyrics: "you", chords: "C#m" },
    ],
    [
      { lyrics: "Aw," },
      { lyrics: "you" },
      { lyrics: "shouldn't" },
      { lyrics: "have" },
    ],
    // Chorus again
    [
      { lyrics: "Oops!", chords: "C#m" },
      { lyrics: "I" },
      { lyrics: "did" },
      { lyrics: "it" },
      { lyrics: "again" },
      { lyrics: "to" },
      { lyrics: "your" },
      { lyrics: "heart" },
    ],
    [
      { lyrics: "Got" },
      { lyrics: "lost" },
      { lyrics: "in" },
      { lyrics: "this" },
      { lyrics: "game," },
      { lyrics: "oh" },
      { lyrics: "baby" },
    ],
    [
      { lyrics: "Oops!...", chords: "C#m" },
      { lyrics: "you" },
      { lyrics: "think" },
      { lyrics: "that" },
      { lyrics: "I'm" },
      { lyrics: "sent" },
      { lyrics: "from" },
      { lyrics: "above", chords: "B" },
    ],
    [
      { lyrics: "I'm" },
      { lyrics: "not" },
      { lyrics: "that" },
      { lyrics: "innocent" },
    ],
    // Repeat chorus (same as before)
  ],
};

async function seedSongs() {
  try {
    await client.connect();
    const db = client.db("Jamoveo");
    const collection = db.collection("songs");

    //await collection.deleteMany({});
    //await collection.insertMany(songs);
    await collection.insertMany([songs]);

    console.log("✅ Songs seeded successfully.");
  } catch (error) {
    console.error("❌ Failed to seed songs:", error);
  } finally {
    await client.close();
  }
}

seedSongs();
